### ISSUE TITLE
Finland prices too cheap

### ISSUE THREAD

**Issue by Saimoni82** [msegzda/homebridge-nordpool-baltics#16]
The hour is 9 and the price shown is 14,9 but really it's 18,4. Same thing for hour 8: price shown was around 30 but was really 37,1. Seems to me that the prices are cents lower than the actual price.

**Comment by iiseppi** [comment]
Prices doesn’t include VAT (ALV).
But maybe developer can add optional VAT prices?

**Comment by msegzda** [comment]
Exactly prices are VAT excluded. It's by plugin design, because VAT and transmission fees are varying across countries and electricity providers. And fees are changing over time. It's just not manageable and to be frank i do not see the point because plugin helps users run equipment on cheapest hours regardless of added fees.
